---
      - local_action: stat path="/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
        register: kibana_exist

      - name: Upload tar.gz Kibana from remote URL
        when: kibana_exist.stat.exists == False
        get_url:
          url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          mode: 0755
          timeout: 60
          force: true
        register: get_kibana
        until: get_kibana is succeeded
        tags: kibana

      - name: Create directory for Kibana
        file:
          mode: 0755
          state: directory
          path: "{{ kibana_home }}"
        tags: kibana

      - name: Extract Kibana in the installation directory
        become: true
        unarchive:
          copy: false
          src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          dest: "{{ kibana_home }}"
          extra_opts: [ --strip-components=1 ]
          creates: "{{ kibana_home }}/bin/kibana"
        tags:
          - skip_ansible_lint
          - kibana

      - name: Set environment Kibana
        become: yes
        template:
          src: templates/elk.sh.j2
          dest: /etc/profile.d/elk.sh
        tags: kibana